require("base")
require("autocmds")
require("options")
require("keymaps")
require("plugins")
require("colorscheme")

-- plugin options
require("bufferline-config")
require("telescope-config")
require("lualine-config")
require("terminal-config")
require("lsp-config")
require("autocomplete-config")
require("treesitter-config")
require("fern")
require("gitsigns-config")
require("surround-config")
require("memo")
